# Generated by Django 3.0.3 on 2020-02-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Issues.Categories'),
        ),
    ]
